apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-quiz-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-quiz
  template:
    metadata:
      labels:
        app: my-quiz
    spec:
      containers:
        - name: my-quiz-container
          image: mecat/countriesiq-image
          ports:
            - containerPort: 3000
