# React Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ciq-service
  name: ciq-service
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    app: ciq-service
  type: LoadBalancer
status:
  loadBalancer: {}

